language: minimal

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - BINTRAY_REPO=custom
    - ARTIFACTORY_URL=https://rpmb.jfrog.io
    - OS7=7.9.2009
    - OS7TAG=7.9.2009

install:
  - docker-compose -f rpmbuild/docker-compose.bintray.yml pull

script:
  - docker-compose build --no-cache
  - docker-compose up
  - docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e ARTIFACTORY_URL=$ARTIFACTORY_URL centos7bintray
